### ISSUE TITLE
ekco purge-node errors if node already deleted

### ISSUE THREAD

**Issue by MikaelSmith** [replicatedhq/ekco#22]
Tried running `ekco purge-node <node>` for a node I'd previously removed with
```
/opt/ekco/shutdown.sh
kubeadm reset
```
and `kubectl delete node <node>`. It errored trying to log with
```
2020-10-27T20:36:52.448Z	INFO	cluster/purge_node.go:17	Purge node "centos-02"
2020-10-27T20:36:52.457Z	INFO	cluster/rook_ceph.go:62	Removing node "centos-02" from CephCluster storage list
2020-10-27T20:36:52.467Z	INFO	cluster/rook_ceph.go:73	Purge node "centos-02": removed from CephCluster node storage list
2020-10-27T20:36:52.556Z	INFO	cluster/rook_ceph.go:104	Deleted OSD Deployment for node centos-02
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1274dbc]

goroutine 1 [running]:
github.com/replicatedhq/ekco/pkg/cluster.(*Controller).PurgeNode(0xc000226800, 0x1849f00, 0xc0000be020, 0x7fff40cfccd4, 0x9, 0x1, 0x0, 0x0)
	/go/src/github.com/replicatedhq/ekco/pkg/cluster/purge_node.go:42 +0x79c
github.com/replicatedhq/ekco/cmd/ekco/cli.purgeNode(0x7fff40cfccd4, 0x9, 0xc000108bd0, 0xc000226800, 0x0, 0xc00051fcf0)
	/go/src/github.com/replicatedhq/ekco/cmd/ekco/cli/purge_node.go:76 +0x2f3
github.com/replicatedhq/ekco/cmd/ekco/cli.PurgeNodeCmd.func2(0xc00022e280, 0xc0002f9ce0, 0x1, 0x1, 0x0, 0x0)
	/go/src/github.com/replicatedhq/ekco/cmd/ekco/cli/purge_node.go:42 +0xca
github.com/spf13/cobra.(*Command).execute(0xc00022e280, 0xc0002f9cb0, 0x1, 0x1, 0xc00022e280, 0xc0002f9cb0)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc000125b80, 0xc000125b80, 0xc0000b6020, 0x1641f3ceeb5fea2a)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/replicatedhq/ekco/cmd/ekco/cli.InitAndExecute(0xc0000aa180, 0x1641f3ceeb5fea2a)
	/go/src/github.com/replicatedhq/ekco/cmd/ekco/cli/root.go:42 +0x1a1
main.main()
	/go/src/github.com/replicatedhq/ekco/cmd/ekco/main.go:14 +0x8b
```

**Comment by MikaelSmith** [comment]
I know I ran this in the wrong order. But seems like most places guard against the node being nil.

**Comment by emosbaugh** [comment]
This was fixed

https://github.com/replicatedhq/ekco/commit/a92292ef293243a3e3ac8c4e7af83cc3aee58737#diff-ad81a0609056246ca9c3a49c3fee9b8e3ffa9526709e717d77e8347cfe81e9c1L42

https://github.com/replicatedhq/ekco/commit/a92292ef293243a3e3ac8c4e7af83cc3aee58737#diff-ad81a0609056246ca9c3a49c3fee9b8e3ffa9526709e717d77e8347cfe81e9c1R113
